# MAIN
MAIN	= main.c
# end MAIN

# ENV
ENV_PARSER = env/envlst_utils.c env/parse.c env/env_utils.c
# end ENV

# LINE
LINE = line/input.c

BUILTIN = builtin/pwd.c builtin/env.c
# end LINE

SRCS = ${MAIN} ${ENV_PARSER} ${LINE} ${BUILTIN}