MAIN	= main.c errors.c

LST_UTILS_FIELS = cmdlst.c envlst.c tokenlst.c
LST_UTILS = $(addprefix lists_utils/,	${LST_UTILS_FIELS})

ENV_PARSER_FILES = parse.c utils.c
ENV_PARSER = $(addprefix env/,	${ENV_PARSER_FILES})

PARSE_FILES = input.c lex_finder.c lexer.c counter.c commands.c
PARSE = $(addprefix parse/, ${PARSE_FILES})

BUILTIN_FILES = pwd.c env.c echo.c unset.c
BUILTIN = $(addprefix builtin/, ${BUILTIN_FILES})

SRCS = ${MAIN} ${ENV_PARSER} ${PARSE} ${BUILTIN} ${LST_UTILS}